-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."bookmarks" drop constraint "bookmarks_user_id_fkey",
--   add constraint "bookmarks_user_id_fkey"
--   foreign key ("user_id")
--   references "public"."users"
--   ("id") on update cascade on delete cascade;
