-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_github_id_key;
-- ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_google_id_key;
