-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."ingredients"
--   add constraint "ingredients_user_id_fkey"
--   foreign key ("user_id")
--   references "public"."users"
--   ("id") on update cascade on delete cascade;
